# Generated by Django 3.0.8 on 2020-10-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20200722_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('first_info', models.CharField(max_length=120)),
                ('second_info', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=50)),
                ('facebook', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
                ('youtube', models.CharField(max_length=50)),
                ('left_credit', models.CharField(max_length=120)),
                ('right_credit', models.CharField(max_length=120)),
            ],
        ),
    ]
